using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Brovan.SourceGen
{
    /// <summary>
    /// Generates compile-time factories that replace the runtime reflection used to build the
    /// Windows syscall dictionary (<c>BuildWinSyscallDictionary</c>) and the Windows device registry
    /// (<c>BuildDeviceRegistry</c>). Discovery mirrors the exact criteria of the reflection it replaces:
    /// non-abstract classes implementing the marker interface within the expected namespace.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class RegistryGenerator : IIncrementalGenerator
    {
        private const string WindowsNs = "Brovan.Core.Emulation.OS.Windows";
        private const string Win32kNs = "Brovan.Core.Emulation.OS.Windows.Win32k";
        private const string IWinSyscall = "Brovan.Core.Emulation.IWinSyscall";
        private const string IWinDevice = "Brovan.Core.Emulation.OS.Windows.IWinDevice";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var data = context.CompilationProvider.Select(static (compilation, _) =>
            {
                INamedTypeSymbol? winIface = compilation.GetTypeByMetadataName(IWinSyscall);
                INamedTypeSymbol? devIface = compilation.GetTypeByMetadataName(IWinDevice);

                var win = new List<string>();
                var win32k = new List<string>();
                var devices = new List<string>();

                foreach (INamedTypeSymbol type in EnumerateNamedTypes(compilation.Assembly.GlobalNamespace))
                {
                    if (type.TypeKind != TypeKind.Class || type.IsAbstract)
                        continue;

                    string ns = type.ContainingNamespace?.ToDisplayString() ?? string.Empty;

                    if (winIface is not null && Implements(type, winIface))
                    {
                        if (ns == WindowsNs)
                            win.Add(type.Name);
                        else if (ns == Win32kNs)
                            win32k.Add(type.Name);
                    }

                    if (devIface is not null && ns == WindowsNs && Implements(type, devIface))
                        devices.Add(type.ToDisplayString());
                }

                win.Sort(StringComparer.Ordinal);
                win32k.Sort(StringComparer.Ordinal);
                devices.Sort(StringComparer.Ordinal);

                return (Win: win.ToImmutableArray(), Win32k: win32k.ToImmutableArray(), Devices: devices.ToImmutableArray());
            });

            context.RegisterSourceOutput(data, static (spc, d) => Emit(spc, d.Win, d.Win32k, d.Devices));
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<string> win, ImmutableArray<string> win32k, ImmutableArray<string> devices)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Brovan.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class GeneratedSyscalls");
            sb.AppendLine("    {");

            sb.Append("        internal static readonly string[] WindowsNames = new string[] { ");
            foreach (string n in win) sb.Append('"').Append(n).Append("\", ");
            sb.AppendLine("};");

            sb.Append("        internal static readonly string[] Win32kNames = new string[] { ");
            foreach (string n in win32k) sb.Append('"').Append(n).Append("\", ");
            sb.AppendLine("};");

            EmitFactory(sb, "CreateWindows", WindowsNs, win);
            EmitFactory(sb, "CreateWin32k", Win32kNs, win32k);

            sb.AppendLine("    }");

            sb.AppendLine("    internal static class GeneratedDevices");
            sb.AppendLine("    {");
            sb.AppendLine("        internal static " + IWinDevice + "[] CreateAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new " + IWinDevice + "[]");
            sb.AppendLine("            {");
            foreach (string d in devices) sb.AppendLine("                new " + d + "(),");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            spc.AddSource("Brovan.Generated.Registry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitFactory(StringBuilder sb, string method, string ns, ImmutableArray<string> names)
        {
            sb.AppendLine("        internal static " + IWinSyscall + "? " + method + "(string name)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (name)");
            sb.AppendLine("            {");
            foreach (string n in names)
                sb.AppendLine("                case \"" + n + "\": return new " + ns + "." + n + "();");
            sb.AppendLine("                default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private static bool Implements(INamedTypeSymbol type, INamedTypeSymbol iface)
        {
            foreach (INamedTypeSymbol i in type.AllInterfaces)
                if (SymbolEqualityComparer.Default.Equals(i, iface))
                    return true;
            return false;
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamespaceSymbol ns)
        {
            foreach (INamespaceOrTypeSymbol member in ns.GetMembers())
            {
                if (member is INamespaceSymbol childNs)
                {
                    foreach (INamedTypeSymbol t in EnumerateNamedTypes(childNs))
                        yield return t;
                }
                else if (member is INamedTypeSymbol type)
                {
                    yield return type;
                    foreach (INamedTypeSymbol nested in EnumerateNested(type))
                        yield return nested;
                }
            }
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateNested(INamedTypeSymbol type)
        {
            foreach (INamedTypeSymbol m in type.GetTypeMembers())
            {
                yield return m;
                foreach (INamedTypeSymbol n in EnumerateNested(m))
                    yield return n;
            }
        }
    }
}
